#!/usr/bin/env python3
"""
Test script to send email via Portia API
This will test the real Portia Gmail integration
"""

import os
import sys
import requests
import json
from pathlib import Path

# Add the backend directory to Python path
backend_dir = Path(__file__).parent
sys.path.append(str(backend_dir))

def test_email_api():
    """Test the email API endpoint"""
    
    email_data = {
        "recipient_email": "pulast9876@gmail.com",
        "analysis_text": """
🎯 PACTGUARD LEGAL ANALYSIS REPORT - TEST EMAIL
==========================================

This is a TEST EMAIL from your PactGuard AI Legal Assistant demonstrating the Portia Gmail integration for AgentHacks2025.

DOCUMENT RISK ANALYSIS:
• Overall Risk Score: 7/10 (HIGH RISK)
• Liability Concerns: 8/10 (CRITICAL)
• Data Privacy Issues: 6/10 (MEDIUM-HIGH)
• Termination Clauses: 7/10 (HIGH)

EXECUTIVE SUMMARY:
The analyzed legal document contains several concerning provisions that require immediate attention. Broad liability waivers limit your legal recourse, while unclear data handling terms create privacy risks.

KEY FINDINGS:
1. Broad liability waiver clause (Section 8.2)
2. Vague data collection terms (Section 4.1) 
3. Unilateral termination rights (Section 12.1)

IMMEDIATE RECOMMENDATIONS:
✅ Schedule legal consultation before signing
✅ Negotiate narrower liability limitations
✅ Request specific data handling details
✅ Consider insurance coverage for excluded risks

This email was sent using the Portia SDK integration.
The API calls will appear in your Portia billing dashboard at:
https://app.portialabs.ai/dashboard/billing

Generated by PactGuard AI Legal Assistant
Powered by Portia AI + Google AI (Gemini)
Open Source Legal AI Platform
""",
        "subject": "🎯 PactGuard Legal Analysis - HIGH RISK DOCUMENT TEST"
    }
    
    try:
        print("🧪 Testing Portia Gmail Integration...")
        print(f"📧 Sending test email to: {email_data['recipient_email']}")
        print(f"📋 Subject: {email_data['subject']}")
        
        response = requests.post(
            "http://127.0.0.1:8001/send-email",
            json=email_data,
            headers={"Content-Type": "application/json"},
            timeout=30
        )
        
        if response.status_code == 200:
            result = response.json()
            print("\n✅ EMAIL SENT SUCCESSFULLY!")
            print(f"📋 Response: {json.dumps(result, indent=2)}")
            
            if result.get("success"):
                print(f"\n🎯 PORTIA API CALL COMPLETED!")
                if "plan_run_id" in str(result):
                    print(f"📋 Plan Run ID: {result.get('details', {}).get('plan_run_id', 'N/A')}")
                print(f"💳 Check your Portia dashboard for billing: https://app.portialabs.ai/dashboard/billing")
                print(f"📧 Check your Gmail inbox: pulast9876@gmail.com")
        else:
            print(f"❌ EMAIL FAILED - Status: {response.status_code}")
            print(f"📋 Response: {response.text}")
            
    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")

if __name__ == "__main__":
    test_email_api()
